# Generated by Django 6.0.2 on 2026-02-11 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('SESS', 'School of Education & Social Sciences'), ('SOBE', 'School of Business & Economics'), ('SCIT', 'School of Computing & Information Technology'), ('SOS', 'School of Science'), ('SOHES', 'School of Health Sciences')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('hod', 'Head of Department'), ('dean', 'Dean'), ('registrar', 'Registrar'), ('admin', 'Admin')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transfer.faculty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='transfer.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('current_year', models.IntegerField()),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('current_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='transfer.program')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('academic_year', models.CharField(max_length=20)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')])),
                ('status', models.CharField(choices=[('pending_hod', 'Pending HOD Review'), ('hod_approved', 'HOD Approved'), ('hod_rejected', 'HOD Rejected'), ('pending_dean', 'Pending Dean Review'), ('dean_approved', 'Dean Approved'), ('dean_rejected', 'Dean Rejected'), ('pending_registrar', 'Pending Registrar Review'), ('registrar_approved', 'Registrar Approved'), ('registrar_rejected', 'Registrar Rejected'), ('completed', 'Completed')], default='pending_hod', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hod_comment', models.TextField(blank=True, null=True)),
                ('dean_comment', models.TextField(blank=True, null=True)),
                ('registrar_comment', models.TextField(blank=True, null=True)),
                ('new_admission_number', models.CharField(blank=True, max_length=20, null=True)),
                ('current_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_from', to='transfer.program')),
                ('requested_program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfer_to', to='transfer.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='transfer.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transfer.transferapplication')),
            ],
        ),
    ]
