# Generated by Django 6.0.2 on 2026-02-11 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(choices=[('SESS', 'School of Education & Social Sciences'), ('SOBE', 'School of Business & Economics'), ('SCIT', 'School of Computing & Information Technology'), ('SOS', 'School of Science'), ('SOHES', 'School of Health Sciences')], max_length=10, unique=True),
        ),
    ]
